extends: 
  - airbnb
  - airbnb/hooks
  - prettier
env:
  browser: true
  es6: true
  node: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 2019
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
    jsx: true
plugins: 
  - prettier
rules:
  prettier/prettier:
    - error
  quotes: 
    - error
    - double
  space-in-parens:
    - error
    - never
  react/jsx-one-expression-per-line:
    - off